version: '2'
services:
  stiger-admin-db-master:
    build:
      context: ./database
      dockerfile: Dockerfile-master
    image: stiger-admin-db-master
    container_name: adminDbMaster13306
    ports:
      - 13306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/Users/snake/docker/container/admin/adminDbMaster13306/data:/var/lib/mysql"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-db-slave1:
    build:
      context: ./database
      dockerfile: Dockerfile-slave
      args:
        server_id: 2
    image: stiger-admin-db-slave1
    container_name: adminDbSlave123306
    ports:
      - 23306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/Users/snake/docker/container/admin/adminDbSlave123306/data:/var/lib/mysql"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-redis:
    image: redis:5.0.8
    container_name: adminRedis16379
    ports:
      - 16379:6379
    volumes:
      - "/Users/snake/docker/container/admin/redis/etc:/usr/local/etc/redis"
      - "/Users/snake/docker/container/admin/redis/data:/data"
  stiger-admin-elastic-search:
    build:
      context: ./elasticsearch
    image: elasticsearch-ik:7.6.2
    container_name: adminElasticSearch19200
    ports:
      - 19200:9200
    environment:
      - discovery.type=single-node
  stiger-admin-elastic-kibana:
    image: kibana:7.6.2
    container_name: adminElasticKibana15601
    ports:
      - 15601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://adminElasticSearch19200:9200
  stiger-admin-elastic-logstash:
    image: logstash:7.6.2
    container_name: adminElasticLogstash19600
    ports:
      - 15044:5044
      - 15055:5055
      - 19600:9600
#    volumes:
#      - "/Users/snake/docker/container/admin/logstash/pipeline:/usr/share/logstash/pipeline"
#      - "/Users/snake/docker/container/admin/logstash/config:/usr/share/logstash/config"
  stiger-admin-web:
    build:
      context: ./star-tiger-admin-web
      args:
        ACTIVE_PROFILE: docker
    image: stiger-admin-web
    container_name: stigerAdminWeb19999
    ports:
      - 19999:9999
    volumes:
      - "/Users/snake/docker/container/admin/web:/opt"
  stiger-admin-endpoint:
    build:
      context: ./star-tiger-admin-endpoint
      args:
        ACTIVE_PROFILE: docker
    image: stiger-admin-endpoint
    container_name: stigerAdminEndpoint19998
    ports:
      - 19998:9998
    volumes:
      - "/Users/snake/docker/container/admin/endpoint:/opt"
