version: '2'
services:
  stiger-admin-db-master:
    build:
      context: ./database
      dockerfile: Dockerfile-master
    image: stiger-admin-db-master
    container_name: adminDbMaster13306
    ports:
      - 13306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/adminDbMaster13306/data:/var/lib/mysql"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-db-slave1:
    build:
      context: ./database
      dockerfile: Dockerfile-slave
      args:
        server_id: 2
    image: stiger-admin-db-slave1
    container_name: adminDbSlave123306
    ports:
      - 23306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/Users/snake/docker/container/mysql/5.7.29/adminDbSlave123306/data:/var/lib/mysql"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  stiger-admin-redis:
    image: redis:5.0.8
    container_name: redis16379
    ports:
      - 16379:6379
    volumes:
      - "/Users/snake/docker/container/redis/5.0.8/etc:/usr/local/etc/redis"
      - "/Users/snake/docker/container/redis/5.0.8/data:/data"
  stiger-admin-web:
    build:
      context: ./star-tiger-admin-web
      args:
        ACTIVE_PROFILE: docker
    image: stiger-admin-web
    container_name: stigerAdminWeb19999
    ports:
      - 19999:9999
  stiger-admin-endpoint:
    build:
      context: ./star-tiger-admin-endpoint
      args:
        ACTIVE_PROFILE: docker
    image: stiger-admin-endpoint
    container_name: stigerAdminEndpoint19998
    ports:
      - 19998:9998
