spring:
  profiles:
    active: ${proj.profile.id}
    include: base,datasource
  application:
    name: ${project.name}
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      ui:
        brand: "<img src=\"images/logo.jpg\"><span>STiger Admin</span>"
        title: "STiger Admin"
        login-icon: "images/logo.jpg"
        favicon: "favicon.ico"
        favicon-danger: "favicon.ico"
        extension-resource-locations:
          - "classpath:/META-INF/spring-boot-admin-server-ui/extensions/"
          - "classpath:/static/"