spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://adminDbMaster13306:3306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: adminRedis16379
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 1m
server:
  port: 9988
  servlet:
    session:
      timeout: 30M