server:
  port: 9998
spring:
  boot:
    admin:
      client:
        url: http://localhost:9988
        username: root
        password: 123456
        instance:
          metadata:
            oauth.resource.server: true
            oauth.token.endpoint: http://127.0.0.1:9999/oauth/token
            client.id: actuator_client
            client.secret: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 16379
#logging:
#  level:
#    org.springframework.security: debug