spring:
  redis:
    host: localhost
    port: 16379
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 1m
  session:
    store-type: redis
  shardingsphere:
    datasource:
      names: ds-master,ds-slave-0
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:13306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
      ds-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:23306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ds-ms
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave-0
    props:
      sql.show: true
server:
  port: 9999
  servlet:
    session:
      timeout: 30M
stiger:
  admin:
    web:
      security:
        remember-me-key: stiger-admin