spring:
  profiles:
    active: ${proj.profile.id}
    include: base
  application:
    name: ${project.name}-${proj.profile.id}
  main:
    allow-bean-definition-overriding: true
stiger:
  frame:
    use-http-status-code: false
  admin:
    web:
      version: ${project.version}
    oauth2:
      enable: true