spring:
  profiles:
    active: ${proj.profile.id}
    include: base,datasource
  application:
    name: ${project.name}-${proj.profile.id}
  main:
    allow-bean-definition-overriding: true
stiger:
  frame:
    use-http-status-code: false
  admin:
    web:
      version: ${project.version}
    oauth2:
      enable: true
logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
#  level:
#      org.springframework.security: debug