spring:
  boot:
    admin:
      client:
        url: http://stigerAdminMonitor19988:9988
        username: root
        password: 123456
        instance:
          metadata:
            user.name: monitor
            user.password: 888888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://adminDbMaster13306:3306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: adminRedis16379
    port: 6379
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 1m
  session:
    store-type: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:oauth-jwt-public-key.txt
server:
  port: 9999
  servlet:
    session:
      timeout: 30M
stiger:
  admin:
    web:
      security:
        remember-me-key: stiger-admin